-- 积存金多渠道：表结构（执行一次）
-- 与 .cursor/plans/积存金多渠道交易_9b7cfd9b.plan.md 一致

CREATE TABLE IF NOT EXISTS `app_user_gold_wallet` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `top_user_id` bigint DEFAULT NULL COMMENT '顶级代理ID（与 app_user_wallet 同步，便于代理维度统计）',
  `wallet_id` bigint NOT NULL COMMENT '关联现金钱包 app_user_wallet.id（HKD 主钱包，用于资金流账变核对）',
  `currency_code` varchar(8) NOT NULL DEFAULT 'HKD' COMMENT '记账币种，默认 HKD',
  `total_grams` decimal(32,16) NOT NULL DEFAULT 0 COMMENT '当前持有总克数（跨所有渠道汇总）',
  `total_cost` decimal(32,16) NOT NULL DEFAULT 0 COMMENT '当前持有部分累计成本（移动平均口径，仅本金，不含手续费）',
  `avg_cost_price` decimal(20,8) NOT NULL DEFAULT 0 COMMENT '当前持有加权成本均价（HKD/克）= total_cost / total_grams',
  `total_invest` decimal(32,16) NOT NULL DEFAULT 0 COMMENT '历史累计买入金额（仅本金）',
  `total_realized_profit` decimal(32,16) NOT NULL DEFAULT 0 COMMENT '历史累计已实现盈亏（含正负，卖出累加）',
  `total_holding_profit` decimal(32,16) NOT NULL DEFAULT 0 COMMENT '最近一次估值聚合的总浮盈',
  `total_market_value` decimal(32,16) NOT NULL DEFAULT 0 COMMENT '最近一次估值聚合的总市值',
  `total_buy_fee` decimal(32,16) NOT NULL DEFAULT 0 COMMENT '历史累计买入手续费',
  `total_sell_fee` decimal(32,16) NOT NULL DEFAULT 0 COMMENT '历史累计卖出手续费',
  `last_evaluate_time` datetime DEFAULT NULL COMMENT '最近一次汇总估值时间',
  `version` int NOT NULL DEFAULT 0 COMMENT '递增版本号',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '0 禁用 1 正常',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_currency` (`user_id`, `currency_code`),
  KEY `idx_wallet` (`wallet_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户积存金账户汇总';

CREATE TABLE IF NOT EXISTS `app_gold_channel` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `channel_code` varchar(64) NOT NULL COMMENT '渠道编码',
  `channel_name` varchar(128) NOT NULL COMMENT '渠道展示名称',
  `bank_name` varchar(128) DEFAULT NULL COMMENT '银行名称',
  `account_label` varchar(64) DEFAULT NULL COMMENT '账户尾号标签',
  `account_tag` varchar(32) DEFAULT NULL COMMENT '账户旗标文案',
  `logo_url` varchar(512) DEFAULT NULL COMMENT '渠道 LOGO 图标 URL',
  `cs_link` varchar(512) DEFAULT NULL COMMENT '客服跳转链接',
  `risk_notice_url` varchar(512) DEFAULT NULL COMMENT '风险提示文章链接',
  `currency_code` varchar(8) NOT NULL DEFAULT 'HKD' COMMENT '渠道记账币种',
  `buy_fee_rate` decimal(20,8) NOT NULL DEFAULT 0 COMMENT '买入手续费率（小数；为 0 时回落到全局配置）',
  `sell_fee_rate` decimal(20,8) NOT NULL DEFAULT 0 COMMENT '卖出手续费率（小数；为 0 时回落到全局配置）',
  `min_buy_amount` decimal(32,16) NOT NULL DEFAULT 0 COMMENT '最小单次买入金额',
  `min_sell_grams` decimal(32,16) NOT NULL DEFAULT 0 COMMENT '最小单次卖出克数',
  `gram_scale` tinyint NOT NULL DEFAULT 4 COMMENT '克数展示小数位',
  `price_tolerance_bps` int NOT NULL DEFAULT 100 COMMENT '前端期望价与服务端价偏离阈值（万分之）',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序',
  `enable_flag` tinyint NOT NULL DEFAULT 1 COMMENT '0 下架 1 上架',
  `remark` varchar(512) DEFAULT NULL COMMENT '后台备注',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_channel_code` (`channel_code`),
  KEY `idx_enable_sort` (`enable_flag`,`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='积存金渠道';

CREATE TABLE IF NOT EXISTS `app_gold_price_quote` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `channel_id` bigint NOT NULL COMMENT '渠道ID',
  `channel_code` varchar(64) NOT NULL COMMENT '渠道编码',
  `price` decimal(20,8) NOT NULL COMMENT '实时价格（HKD/克）',
  `prev_close_price` decimal(20,8) DEFAULT NULL COMMENT '前日收盘价',
  `change_amount` decimal(20,8) DEFAULT NULL COMMENT '相对前收涨跌额',
  `change_pct` decimal(20,8) DEFAULT NULL COMMENT '相对前收涨跌幅（小数）',
  `intraday_high` decimal(20,8) DEFAULT NULL COMMENT '当日最高价',
  `intraday_low` decimal(20,8) DEFAULT NULL COMMENT '当日最低价',
  `intraday_open` decimal(20,8) DEFAULT NULL COMMENT '当日开盘价',
  `quote_time` datetime NOT NULL COMMENT '行情更新时间',
  `trading_status` tinyint NOT NULL DEFAULT 1 COMMENT '0 休市 1 交易中 2 已收盘',
  `volume` decimal(32,16) NOT NULL DEFAULT 0 COMMENT '当日累计成交克数',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_channel` (`channel_id`),
  KEY `idx_channel_code` (`channel_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='积存金渠道实时金价';

CREATE TABLE IF NOT EXISTS `app_gold_position` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `gold_wallet_id` bigint NOT NULL COMMENT '关联积存金钱包',
  `cash_wallet_id` bigint NOT NULL COMMENT '关联现金钱包',
  `channel_id` bigint NOT NULL COMMENT '渠道ID',
  `channel_code` varchar(64) NOT NULL COMMENT '渠道编码',
  `currency_code` varchar(8) NOT NULL DEFAULT 'HKD' COMMENT '币种',
  `channel_name_snapshot` varchar(128) DEFAULT NULL COMMENT '建仓时渠道名称快照',
  `account_label_snapshot` varchar(64) DEFAULT NULL COMMENT '建仓时账户标签快照',
  `hold_grams` decimal(32,16) NOT NULL DEFAULT 0 COMMENT '当前持有克数',
  `hold_cost` decimal(32,16) NOT NULL DEFAULT 0 COMMENT '当前持有部分累计成本',
  `cost_avg_price` decimal(20,8) NOT NULL DEFAULT 0 COMMENT '成本均价（HKD/克）',
  `last_market_value` decimal(32,16) NOT NULL DEFAULT 0 COMMENT '最近一次估值',
  `last_holding_profit` decimal(32,16) NOT NULL DEFAULT 0 COMMENT '最近一次持仓浮盈',
  `cumulative_profit` decimal(32,16) NOT NULL DEFAULT 0 COMMENT '累计已实现盈亏',
  `cumulative_invest` decimal(32,16) NOT NULL DEFAULT 0 COMMENT '该渠道历史累计买入金额',
  `cumulative_buy_fee` decimal(32,16) NOT NULL DEFAULT 0 COMMENT '该渠道累计买入手续费',
  `cumulative_sell_fee` decimal(32,16) NOT NULL DEFAULT 0 COMMENT '该渠道累计卖出手续费',
  `today_profit` decimal(32,16) NOT NULL DEFAULT 0 COMMENT '当日盈亏',
  `today_profit_date` date DEFAULT NULL COMMENT '当日盈亏统计的自然日',
  `last_buy_time` datetime DEFAULT NULL COMMENT '最近一次买入时间',
  `last_sell_time` datetime DEFAULT NULL COMMENT '最近一次卖出时间',
  `last_evaluate_time` datetime DEFAULT NULL COMMENT '最近一次估值时间',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '0 禁用 1 正常',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_channel` (`user_id`,`channel_id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_channel` (`channel_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户积存金渠道持仓';

CREATE TABLE IF NOT EXISTS `app_gold_order` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_no` varchar(64) NOT NULL COMMENT '订单号',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `gold_wallet_id` bigint NOT NULL COMMENT '积存金钱包ID',
  `cash_wallet_id` bigint NOT NULL COMMENT 'HKD 现金钱包ID',
  `channel_id` bigint NOT NULL COMMENT '渠道ID',
  `channel_code` varchar(64) NOT NULL COMMENT '渠道编码',
  `currency_code` varchar(8) NOT NULL DEFAULT 'HKD' COMMENT '币种',
  `channel_name_snapshot` varchar(128) DEFAULT NULL COMMENT '成交时渠道名称快照',
  `account_label_snapshot` varchar(64) DEFAULT NULL COMMENT '成交时账户标签快照',
  `direction` tinyint NOT NULL COMMENT '方向：1 买入 2 卖出',
  `price` decimal(20,8) NOT NULL COMMENT '成交单价（HKD/克）',
  `expect_price` decimal(20,8) DEFAULT NULL COMMENT '前端展示的期望价',
  `grams` decimal(32,16) NOT NULL COMMENT '成交克数',
  `amount` decimal(32,16) NOT NULL COMMENT '成交金额（不含手续费）',
  `fee_rate` decimal(20,8) NOT NULL DEFAULT 0 COMMENT '手续费率快照',
  `fee_amount` decimal(32,16) NOT NULL DEFAULT 0 COMMENT '手续费金额',
  `wallet_change_amount` decimal(32,16) NOT NULL COMMENT '现金钱包实际变动金额',
  `cost_avg_price_before` decimal(20,8) DEFAULT NULL COMMENT '成交前的成本均价快照',
  `cost_avg_price_after` decimal(20,8) DEFAULT NULL COMMENT '成交后的成本均价快照',
  `realized_profit` decimal(32,16) DEFAULT NULL COMMENT '本笔实现盈亏',
  `realized_profit_net` decimal(32,16) DEFAULT NULL COMMENT '本笔实现盈亏（扣手续费后）',
  `quote_id` bigint DEFAULT NULL COMMENT '关联行情ID',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '0 处理中 1 已成交 -1 失败',
  `fail_reason` varchar(512) DEFAULT NULL COMMENT '失败原因',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  `finish_time` datetime DEFAULT NULL COMMENT '成交时间',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_no` (`order_no`),
  KEY `idx_user_status_time` (`user_id`,`status`,`create_time`),
  KEY `idx_user_channel_dir` (`user_id`,`channel_id`,`direction`),
  KEY `idx_channel_time` (`channel_id`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='积存金买卖订单';

CREATE TABLE IF NOT EXISTS `app_gold_global_config` (
  `id` tinyint NOT NULL DEFAULT 1 COMMENT '主键固定 1',
  `default_buy_fee_rate` decimal(20,8) NOT NULL DEFAULT 0 COMMENT '默认买入手续费率（小数）',
  `default_sell_fee_rate` decimal(20,8) NOT NULL DEFAULT 0 COMMENT '默认卖出手续费率（小数）',
  `default_min_buy_amount` decimal(32,16) NOT NULL DEFAULT 0 COMMENT '默认最低买入金额',
  `default_min_sell_grams` decimal(32,16) NOT NULL DEFAULT 0 COMMENT '默认最低卖出克数',
  `default_gram_scale` tinyint NOT NULL DEFAULT 4 COMMENT '默认克数小数位',
  `default_price_tolerance_bps` int NOT NULL DEFAULT 100 COMMENT '默认价格偏离阈值（万分之）',
  `currency_code` varchar(8) NOT NULL DEFAULT 'HKD' COMMENT '业务记账币种',
  `quote_cache_seconds` int NOT NULL DEFAULT 5 COMMENT '行情 Redis 缓存秒数',
  `risk_notice_url` varchar(512) DEFAULT NULL COMMENT '通用风险提示链接',
  `entry_enable` tinyint NOT NULL DEFAULT 1 COMMENT '入口总开关',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='积存金全局配置';

INSERT IGNORE INTO `app_gold_global_config` (`id`) VALUES (1);
